#+TITLE: Brief Student Auto-biography
#+AUTHOR: George Rushevich

George Rushevich is rounding out his Bachelor’s Degree in Computer Engineering at the University of Florida, having also achieved a minor in Physics (focusing predominantly on modern physics fields like quantum mechanics). George is a driven individual with a notable thirst and curiosity for knowledge, that has led him through a wide scope of disciplines within the industries pertaining to computer sciences and engineering. Principally, George strives to become an expert of low-level software and systems engineering, and he carries a deep interest for the C++ programming language, aiming to apply this in performance-critical and high-caliber fields such as high-frequency-trading and distributed systems work.

Having been conditionally accepted through a gauranteed-transfer pathway to the University of Florida after high-school, the tone was set for George quite early in his higher-education career. The dissatisfaction with having been dealt a different hand led him to develop strong executive-functioning skills. Thereafter, George spent the majority of his time as an undergraduate pursuing a potential career in the semiconductor industry, after being deeply inspired and intrigued by a historical review of the industry (titled "Chip War"). Having worked as an undergraduate researcher at the Florida Institute for National Security under Dr. Domenic Forte, George gained a nuanced perspective unto the world of semiconductor process and IP (intellectual property) security.

In transitioning to the upperclassman years, George once again was inspired deeply by an engineering discipline. The technical depth and rigor of computer science both historically and currently has led to him asserting a tremendous interest in low-level software engineering, specifically with the C++ programming language. A testament to his ability to lead and effectively forward his passions to those around him, he founded the C++ Club at UF this Fall, and has quickly grown its roster to beyond 20 members. He continues to apply his interest outside of his educational and professional career through personal projects, literature, and conferences.

Beyond the classroom, George applies his discipline and his drive through physically challenging sports and actvities, including climbing and sprinting. George strives to always progress in whatever activities he takes on, and believes in the importance to always grow, develop, and make progress. He loves to read, and is currently interested in topics like economics / finance, philosophy, and languages. Coming from Russian blood, George is fluent in Russian, and also spent a summer studying in Kyoto, Japan, picking up a basic level of the Japanese language along the way.

Growing up in a small town in the north-east (Wilton, Connecticut), George is fond of quiet and peaceful times in life, and his ultimate goal in life is to be able to surround himself with friends and family that appreciate the simple things of life, and leave a lasting impact on the world through meaningful work as an engineer.
